### ISSUE TITLE
The plugin does not work in version 10.10.0

### ISSUE THREAD

**Issue by Druidblack** [EusthEnoptEron/jellyfin-plugin-animethemes#9]
When starting a task from the scheduler, the plugin is installed with a failure.

Rolling back to version 10.9.11 solved the problem with performance.

**Comment by EusthEnoptEron** [comment]
Thanks for reporting!

I released a version that should work with 10.10.0.

**Note**: I messed up the Checksum on my first try, so if you get an error while upgrading, try again later when the cache has been invalidated.
